name: prowlarr
services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediaserver"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: America/Sao_Paulo
    volumes:
      - prowlarr:/config
    networks:
      - mediaserver

volumes:
  prowlarr:
    external: true

networks:
  mediaserver:
    name: mediaserver
    external: true
