name: homeassistant
services:
  homeassistant:
    image: ghcr.io/onedr0p/home-assistant:rolling
    container_name: homeassistant
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=services"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN}`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    networks:
      - mediaserver
      - services

volumes:
  homeassistant:
    name: homeassistant
    external: true

networks:
  mediaserver:
    name: mediaserver
    external: true
  services:
    name: services
    external: true
