name: radarr
services:
  radarr:
    container_name: radarr
    image: ghcr.io/onedr0p/radarr:rolling
    restart: unless-stopped
    user: ${PUID}:${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediaserver"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    volumes:
      - radarr:/config
      - Movies:/storage/Movies:rw
      - Completed:/storage/Completed:rw
    networks:
      - mediaserver

volumes:
  radarr:
    external: true
  Movies:
    external: true
  Completed:
    external: true

networks:
  mediaserver:
    name: mediaserver
    external: true
