name: deluge
services:
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediaserver"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.entrypoints=websecure"
      - "traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN}`)"
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    volumes:
      - deluge:/config
      - Movies:/storage/Movies:rw
      - Series:/storage/Series:rw
      - Completed:/storage/Completed:rw
      - downloading:/storage/.downloading:rw
    networks:
      - mediaserver

volumes:
  deluge:
    external: true
  Movies:
    external: true
  Series:
    external: true
  Completed:
    external: true
  downloading:
    external: true

networks:
  mediaserver:
    name: mediaserver
    external: true
