name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    user: ${PUID}:${PGID}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediaserver"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: America/Sao_Paulo
    group_add:
      - "989"
      - "985"
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - jellyfin:/config
      - /media/Downloads/jellyfin_metadata/metadata/:/config/metadata/
      - Movies:/storage/Movies:rw
      - Series:/storage/Series:rw
      - Completed:/storage/Completed:rw
    networks:
      - mediaserver

volumes:
  jellyfin:
    external: true
  Movies:
    external: true
  Series:
    external: true
  Completed:
    external: true

networks:
  mediaserver:
    name: mediaserver
    external: true
